version: "3.8"

services:
  php:
    build: .
    container_name: php_container
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
